---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: tomcat-servers
  remote_user: root
  become: yes
  become_method: sudo

  roles:
  #  - selinux must be updated to be conform with os version
    - tomcat
